name: app_clinica
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2 # Para lidar com datas/agendamento
  shared_preferences: ^2.2.2 # Para salvar a preferência do usuário

  # Pacotes
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  intl: ^0.18.1
  table_calendar: ^3.0.9
  path_provider: ^2.1.3
  open_file: ^3.3.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

# Configuração do Ícone do App (Opcional, se você usar o flutter_launcher_icons)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

# --- AQUI ESTAVA O ERRO ---
# A palavra 'flutter:' deve estar encostada na margem esquerda
flutter:
  uses-material-design: true
  
  # Aqui definimos onde estão as imagens
  assets:
    - assets/images/